# Each scene: (title, [beats]); beat = caption or (caption, tts_text)
SCENES = [
 ("Distributed Key Generation", [
  ("This is a short tour of distributed key generation, or DKG, as implemented in the near/mpc repository.",
   "This is a short tour of distributed key generation, or D K G, as implemented in the near M P C repository."),
  ("By the end, you'll know how a group of nodes creates a shared signing key that no single node ever sees.", None),
 ]),
 ("The problem", [
  ("Our MPC network signs on behalf of users. To do that, it needs one master key pair.",
   "Our M P C network signs on behalf of users. To do that, it needs one master key pair."),
  ("The public key can be known by everyone. But the private key must never exist in one place — not on any node, not even for a moment.", None),
  ("Instead, each of the N nodes holds a share. Any t of them — the reconstruction threshold — can sign together. Fewer than t learn nothing.",
   "Instead, each of the N nodes holds a share. Any T of them, the reconstruction threshold, can sign together. Fewer than T learn nothing."),
 ]),
 ("Shamir secret sharing", [
  ("The basic tool is Shamir secret sharing. Pick a random polynomial f of degree t − 1.",
   "The basic tool is Shamir secret sharing. Pick a random polynomial, f, of degree T minus one."),
  ("The secret is the value at zero, f(0). Node j's share is f(j).",
   "The secret is the value at zero, f of zero. Node J's share is f of J."),
  ("Any t points pin down the polynomial, so t shares recover the secret. With only t − 1 points, every secret is still equally possible.",
   "Any T points pin down the polynomial, so T shares recover the secret. With only T minus one points, every secret is still equally possible."),
  ("But whoever picks f knows the secret. In a DKG, there is no trusted dealer.",
   "But whoever picks f knows the secret. In a D K G, there is no trusted dealer."),
 ]),
 ("Everyone is a dealer", [
  ("Instead, every node i samples its own random polynomial fᵢ.",
   "Instead, every node, I, samples its own random polynomial, f I."),
  ("Node i privately sends the evaluation fᵢ(j) to every node j.",
   "Node I privately sends the evaluation f I of J to every node J."),
  ("Node j adds up everything it received. That sum is its final share skⱼ — a point on the combined polynomial F, the sum of all the fᵢ.",
   "Node J adds up everything it received. That sum is its final share, S K J. It is a point on the combined polynomial, capital F, the sum of all the f I."),
  ("The master secret is F(0), the sum of every node's contribution. Nobody ever computes it, and as long as one node is honest, it stays uniformly random.",
   "The master secret is capital F of zero, the sum of every node's contribution. Nobody ever computes it, and as long as one node is honest, it stays uniformly random."),
 ]),
 ("Commitments and the public key", [
  ("Each node also publishes a commitment to its polynomial: every coefficient multiplied by the curve generator G.",
   "Each node also publishes a commitment to its polynomial: every coefficient multiplied by the curve generator, G."),
  ("The master public key is the sum of the constant-term commitments Cᵢ(0). Every node computes the same one.",
   "The master public key is the sum of the constant term commitments, C I of zero. Every node computes the same one."),
  ("Commitments also make shares verifiable: fⱼ(i)·G must match the commitment polynomial evaluated at i. A node that sends a bad share is caught.",
   "Commitments also make shares verifiable. f J of I, times G, must match the commitment polynomial evaluated at I. A node that sends a bad share is caught."),
 ]),
 ("PedPop+: stopping cheaters", [
  ("A naive sum is fragile against an adversary who moves last. So our variant, PedPop+, adds three defenses.",
   "A naive sum is fragile against an adversary who moves last. So our variant, Ped Pop plus, adds three defenses."),
  ("First, a Schnorr proof of knowledge of fᵢ(0). This blocks rogue-key attacks, where a cheater picks its commitment to cancel everyone else's and control the final key.",
   "First, a Schnorr proof of knowledge of f I of zero. This blocks rogue key attacks, where a cheater picks its commitment to cancel everyone else's, and control the final key."),
  ("Second, commit before reveal: each node first sends a hash of its commitment, and only later reveals it. Nobody can adapt after seeing the others.", None),
  ("Third, reliable echo broadcast, so every honest node sees exactly the same messages. A node can't tell different stories to different peers.", None),
  ("Everything is bound to a session ID, hashed from random contributions of all nodes, so messages can't be replayed across runs.",
   "Everything is bound to a session I D, hashed from random contributions of all nodes, so messages can't be replayed across runs."),
 ]),
 ("The protocol, round by round", [
  ("Here are the rounds as implemented in do_keyshare, in dkg.rs.",
   "Here are the rounds, as implemented in do keyshare, in D K G dot R S."),
  ("Round 1: broadcast a random session-ID contribution. Round 2: derive the session ID, sample the polynomial, compute commitment and proof, and send the commitment hash.",
   "Round one: broadcast a random session I D contribution. Round two: derive the session I D, sample the polynomial, compute the commitment and proof, and send the commitment hash."),
  ("Round 3: reliably broadcast commitments and proofs. Round 4: verify every proof and hash, compute the public key, and privately send each peer its share.",
   "Round three: reliably broadcast commitments and proofs. Round four: verify every proof and hash, compute the public key, and privately send each peer its share."),
  ("Round 5: check received shares against the commitments and sum them into the secret share. Finally, everyone broadcasts success and outputs the key pair.",
   "Round five: check received shares against the commitments, and sum them into the secret share. Finally, everyone broadcasts success, and outputs the key pair."),
  ("Three steps use echo broadcast, which takes three message rounds itself — about eleven and a half rounds on the wire in total.", None),
 ]),
 ("Running it in production", [
  ("In production, the contract drives everything. When it enters the Initializing state, a leader node calls start_keygen.",
   "In production, the contract drives everything. When it enters the initializing state, a leader node calls start keygen."),
  ("All participants join the computation over the TLS peer-to-peer mesh. Each node stores its key share locally, then calls vote_pk with the public key.",
   "All participants join the computation over the T L S peer to peer mesh. Each node stores its key share locally, then calls vote P K with the public key."),
  ("The contract accepts the key only when every participant votes for the same public key. A disagreement aborts the attempt, and the leader retries.", None),
  ("This repeats per domain: the same generic protocol yields secp256k1 keys for ECDSA, Ed25519 keys for EdDSA, and BLS12-381 keys for confidential key derivation. Then the contract is Running.",
   "This repeats per domain. The same generic protocol yields secp two five six k one keys for E C D S A, ed twenty five five nineteen keys for Ed D S A, and B L S twelve three eighty one keys for confidential key derivation. Then the contract is running."),
 ]),
 ("Resharing and refresh", [
  ("The same core function also handles resharing, when the participant set or threshold changes.", None),
  ("Old holders set their constant term to λᵢ · secretᵢ, their share weighted by a Lagrange coefficient. New joiners use zero. The sum is the same master secret, split among the new set.",
   "Old holders set their constant term to lambda I times secret I, their share weighted by a Lagrange coefficient. New joiners use zero. The sum is the same master secret, split among the new set."),
  ("Finally, everyone asserts that the new public key equals the old one. Refresh is the special case with the same participants: fresh shares, same key.", None),
 ]),
 ("Recap", [
  ("Every node contributes randomness. Shares travel privately. Commitments make them verifiable. Proofs and broadcast stop cheaters. The contract confirms the result.", None),
  ("The public key is known to all; the private key exists nowhere. Full spec: crates/threshold-signatures/docs/dkg.md.",
   "The public key is known to all. The private key exists nowhere. For the full spec, see the D K G doc in the threshold signatures crate."),
 ]),
]
