[package]
name = "test_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
attestation = { workspace = true }
contract-interface = { workspace = true }
dstack-sdk-types = { workspace = true }
hex = { workspace = true }
mpc-primitives = { workspace = true }
near-sdk = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
