[package]
name = "test_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
interfaces = { workspace = true }
attestation = { workspace = true }
ed25519-dalek = { workspace = true }
mpc-primitives = { workspace = true }
hex = { workspace = true }
near-sdk = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
regex = { workspace = true }
