[package]
name = "attestation-types"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
borsh-schema = ["borsh/unstable__schema"]
dstack-conversions = ["dep:dstack-sdk-types"]

[dependencies]
borsh = { workspace = true }
derive_more = { workspace = true }
dstack-sdk-types = { workspace = true, optional = true }
hex = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
dstack-sdk-types = { workspace = true }
rstest = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
