# [container]
# image = "docker.io/rust:1.86-slim-bookworm"

# [packages]
# system = "debian"
# dependencies = ["make", "git", "libssl-dev", "pkg-config", "clang"]
[container]
image = "docker.io/library/archlinux"

[packages]
system = "archlinux"
dependencies = ["openssl", "clang", "base-devel", "rustup"]