APP_NAME="${APP_NAME}"
VMM_RPC=${VMM_RPC}
SEALING_KEY_TYPE=${SEALING_KEY_TYPE}

EXTERNAL_DSTACK_AGENT_PORT=${EXTERNAL_DSTACK_AGENT_PORT}
EXTERNAL_SSH_PORT=${EXTERNAL_SSH_PORT}

EXTERNAL_MPC_PUBLIC_DEBUG_PORT=${EXTERNAL_MPC_PUBLIC_DEBUG_PORT}
EXTERNAL_MPC_LOCAL_DEBUG_PORT=${EXTERNAL_MPC_LOCAL_DEBUG_PORT}
EXTERNAL_MPC_DECENTRALIZED_STATE_SYNC=${EXTERNAL_MPC_DECENTRALIZED_STATE_SYNC}
EXTERNAL_MPC_MAIN_PORT=${EXTERNAL_MPC_MAIN_PORT}
EXTERNAL_MPC_FUTURE_PORT=${EXTERNAL_MPC_FUTURE_PORT}

INTERNAL_MPC_PUBLIC_DEBUG_PORT=${INTERNAL_MPC_PUBLIC_DEBUG_PORT}
INTERNAL_MPC_LOCAL_DEBUG_PORT=${INTERNAL_MPC_LOCAL_DEBUG_PORT}
INTERNAL_MPC_DECENTRALIZED_STATE_SYNC=${INTERNAL_MPC_DECENTRALIZED_STATE_SYNC}
INTERNAL_MPC_MAIN_PORT=${INTERNAL_MPC_MAIN_PORT}
INTERNAL_MPC_FUTURE_PORT=${INTERNAL_MPC_FUTURE_PORT}

OS_IMAGE=${OS_IMAGE}
DOCKER_COMPOSE_FILE_PATH=${DOCKER_COMPOSE_FILE_PATH}
USER_CONFIG_FILE_PATH=${USER_CONFIG_FILE_PATH}

DISK=${DISK}
