MPC_IMAGE_NAME=${MPC_IMAGE_NAME}
MPC_IMAGE_TAGS=${MPC_IMAGE_TAGS}
MPC_REGISTRY=${MPC_REGISTRY}

MPC_ACCOUNT_ID=${MPC_ACCOUNT_ID}
MPC_LOCAL_ADDRESS=127.0.0.1
MPC_SECRET_STORE_KEY=${MPC_SECRET_STORE_KEY}
MPC_CONTRACT_ID=${MPC_CONTRACT_ID}
MPC_ENV=${MPC_ENV}
MPC_HOME_DIR=/data
RUST_BACKTRACE=full
RUST_LOG=info

NEAR_BOOT_NODES=${NEAR_BOOT_NODES}

PORTS=${PORTS}
