// Include build information generated by the built crate
#[expect(
    clippy::allow_attributes,
    reason = "built.rs files are included verbatim and use allow()"
)]
pub(crate) mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

use std::sync::LazyLock;

pub static MPC_VERSION_STRING: LazyLock<String> = LazyLock::new(|| {
    format!(
        "mpc-node {}\n(release {}) (build_time {}) (commit {}) ({})",
        built_info::PKG_VERSION,
        built_info::PKG_VERSION,
        built_info::BUILT_TIME_UTC,
        built_info::GIT_COMMIT_HASH_SHORT.unwrap_or("unknown"),
        built_info::RUSTC_VERSION,
    )
});

pub mod cli;
pub mod config;
pub mod keyshare;
pub mod metrics;
pub mod migration_service;
pub mod p2p;
pub mod primitives;
pub mod requests;
pub mod tracing;
pub mod types;
pub mod web;

pub(crate) mod profiler;
pub(crate) mod trait_extensions;

mod assets;
#[cfg(test)]
mod async_testing;
mod background;
mod coordinator;
mod db;
mod foreign_chain_policy;
mod foreign_chain_probe;
mod foreign_chain_whitelist_verifier;
mod home_paths;
mod indexer;
mod key_events;
mod mpc_client;
mod network;
mod protocol;
mod protocol_version;
mod providers;
mod run;
mod runtime;
mod storage;
mod tee;
#[cfg(test)]
mod tests;
mod tracking;
