# Overrides https://github.com/near/.github/blob/main/.github/ISSUE_TEMPLATE/new-task.yml

name: New Task
description: Create a new work task.
labels: ["issue"]
body:
  - type: markdown
    attributes:
      value: "## 📝 New Task"

  - type: textarea
    id: background
    attributes:
      label: "Background"
      placeholder: "Brief description of what this task will accomplish. What is the goal and why should this be done?"
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: "User Story"
      placeholder: "Describe who are we solving for, their need, and why. (Example: \"As an admin, I need to have a way to add members so that my entire team can participate in our governance\")"

  - type: textarea
    id: done
    attributes:
      label: "Acceptance Criteria"
      placeholder: "What exactly needs to be done to mark this issue as complete?(Add a task list if needed)"
      value:
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "Resources & Additional Notes"
      placeholder: "Any relevant resources, extra context, links, or screenshots?"
