services:
  launcher:
    image: nearone/mpc-launcher@sha256:02ba809689637d13a9e28b31a9e00de4fef776f3d604bdd51c5a03ee756eb316
    container_name: "${LAUNCHER_IMAGE_NAME}"

    environment:
      - PLATFORM=NONTEE
      - DOCKER_CONTENT_TRUST=1
      - DEFAULT_IMAGE_DIGEST=sha256:6a5700fccbb3facddd1f3934f4976c4dcefc176c4aac28cd2fd035984b368980

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./user-config.toml:/tapp/user_config:ro
      - shared-volume:/mnt/shared:rw
      - mpc-data:/data

    security_opt:
      - no-new-privileges:true

    read_only: true
    tmpfs:
      - /tmp

volumes:
  shared-volume:
    name: shared-volume
  mpc-data:
    name: mpc-data
