version: '3.8'

services:
  launcher:
    image: nearone/mpc-launcher@sha256:5308ee3fd43459e239a71fec6facb4a1c42bb78f823d64386051db20ae739aec

    container_name: launcher

    environment:
      - PLATFORM=TEE
      - DOCKER_CONTENT_TRUST=1
      - DEFAULT_IMAGE_DIGEST=sha256:5d1e604dcf3197f8b465c854f8073eaa89b9733f646248d59f86a15b81110ef5

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dstack.sock:/var/run/dstack.sock
      - /tapp:/tapp:ro
      - shared-volume:/mnt/shared:rw

    security_opt:
      - no-new-privileges:true

    read_only: true

    tmpfs:
      - /tmp

volumes:
  shared-volume:
    name: shared-volume
