services:
  launcher:
    image: nearone/mpc-launcher@sha256:b27bd03d1fa3636a899a9e846bbb6e4dbad28953e660e087b0f3de44745308f4
    container_name: "${RUST_LAUNCHER_IMAGE_NAME}"

    environment:
      - PLATFORM=NONTEE
      - DOCKER_CONTENT_TRUST=1
      - DEFAULT_IMAGE_DIGEST=sha256:5d1e604dcf3197f8b465c854f8073eaa89b9733f646248d59f86a15b81110ef5

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./user-config.toml:/tapp/user_config:ro
      - shared-volume:/mnt/shared:rw
      - mpc-data:/data

    security_opt:
      - no-new-privileges:true

    read_only: true
    tmpfs:
      - /tmp

volumes:
  shared-volume:
    name: shared-volume
  mpc-data:
    name: mpc-data
