[package]
name = "foreign-chain-health-check"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
foreign-chain-inspector = { workspace = true }
futures = { workspace = true }
mpc-node-config = { workspace = true }
near-mpc-bounded-collections = { workspace = true }
near-mpc-contract-interface = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
foreign-chain-inspector = { workspace = true, features = ["test-utils"] }
foreign-chain-rpc-factory = { workspace = true }
foreign-chain-rpc-interfaces = { workspace = true }
http = { workspace = true }
httpmock = { workspace = true }
rstest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true, features = ["codegen", "router", "server"] }

[lints]
workspace = true
