FROM debian:bookworm-slim@sha256:acd98e6cfc42813a4db9ca54ed79b6f702830bfc2fa43a2c2e87517371d82edb AS download
ARG COMPOSE_VERSION=v2.37.0
ARG COMPOSE_SHA256=e6e471b1e7bf0443592d3987dea6073f08db3e48ba0580199109aa7a44257e54
ADD https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-linux-x86_64 /docker-compose
RUN echo "${COMPOSE_SHA256}  /docker-compose" | sha256sum -c -

FROM debian:bookworm-slim@sha256:acd98e6cfc42813a4db9ca54ed79b6f702830bfc2fa43a2c2e87517371d82edb
ENV DEBIAN_FRONTEND=noninteractive

# Install packages with exact versions for reproducibility
RUN \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    --mount=type=bind,source=./deployment/repro-sources-list.sh,target=/usr/local/bin/repro-sources-list.sh \
    repro-sources-list.sh && \
    apt-get update && \
    apt-get install -y --no-install-recommends docker.io && \
    : "Clean up for improving reproducibility" && \
    rm -rf /var/log/* /var/cache/ldconfig/aux-cache

COPY --from=download --chmod=0755 /docker-compose /usr/local/lib/docker/cli-plugins/docker-compose

COPY --chmod=0755 target/reproducible/tee-launcher /usr/local/bin/tee-launcher
RUN mkdir -p /app-data && mkdir -p /mnt/shared
CMD ["tee-launcher"]
