# FROM debian:bookworm-slim@sha256:4b44499bc2a6c78d726f3b281e6798009c0ae1f034b0bfaf6a227147dcff928b
FROM rust:1.86-bullseye@sha256:3ae85170272532616218575edad2310507f72991766775d095a82acf56b29fd6

# https://snapshot.debian.org/archive/debian/20241201T025825Z/
# ARG SNAP=20241201T025825Z

# RUN set -eux; \
#   echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99snapshot; \
#   cat > /etc/apt/sources.list <<EOF
# deb http://snapshot.debian.org/archive/debian/${SNAP} bookworm main contrib non-free-firmware
# deb http://snapshot.debian.org/archive/debian/${SNAP} bookworm-updates main contrib non-free-firmware
# deb http://snapshot.debian.org/archive/debian-security/${SNAP} bookworm-security main contrib non-free-firmware
# deb http://snapshot.debian.org/archive/debian-debug/${SNAP} bookworm-debug main
# EOF

# Install packages with exact versions for reproducibility
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        docker.io=20.10.5+dfsg1-1+deb11u4 \
        docker-compose=1.25.0-1 \
        curl=7.74.0-1.3+deb11u15 \
        jq=1.6-2.1 \
        bash=5.1-2+deb11u1 \
        coreutils=8.32-4+b1 \
        python3=3.9.2-3 && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/log/* /var/cache/ldconfig/aux-cache

COPY tee_launcher/launcher.py /scripts/
RUN chmod +x /scripts/launcher.py
ENV PATH="/scripts:${PATH}"
RUN mkdir -p /app-data
RUN mkdir -p /mnt/shared
CMD ["python3", "/scripts/launcher.py"]
