FROM rust:1.86 AS builder
RUN apt-get update -y && apt-get install -y --no-install-recommends clang  # needed for rocksdb

WORKDIR /app
COPY .git .git
COPY crates crates
COPY Cargo.lock Cargo.lock
COPY Cargo.toml Cargo.toml
COPY rust-toolchain.toml rust-toolchain.toml
COPY third-party-licenses third-party-licenses

RUN cargo build --locked --release

FROM google/cloud-sdk:debian_component_based AS runtime
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends openssl ca-certificates

ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

WORKDIR /app
COPY --from=builder /app/target/release/mpc-node mpc-node
COPY deployment/start.sh /app/start.sh
RUN chmod +x /app/start.sh
CMD [ "/app/start.sh" ]