FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates openssl python3 && \
    rm -rf /var/lib/apt/lists/*
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
WORKDIR /app
COPY target/reproducible/mpc-node mpc-node
COPY --chmod=0755 deployment/start.sh /app/start.sh
COPY --chmod=0755 deployment/localnet/genesis.json /app/localnet-genesis.json
CMD [ "/app/start.sh" ]
