services:
  launcher:
    image: nearone/mpc-launcher@sha256:a4d870b0eee3a55b3c5e94b3707e85fb50e5de64eb6be65ef2d27426616c95f9
    container_name: "${LAUNCHER_IMAGE_NAME}"

    environment:
      - PLATFORM=NONTEE
      - DOCKER_CONTENT_TRUST=1
      - DEFAULT_IMAGE_DIGEST=sha256:e7d1df7453b9bb9e89969f02a0ae59c3c2743cd895963e97a8e7666defbf4dab # latest main with config file support

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./user-config.toml:/tapp/user_config:ro
      - shared-volume:/mnt/shared
      - mpc-data:/data

    security_opt:
      - no-new-privileges:true

    read_only: true
    tmpfs:
      - /tmp

volumes:
  shared-volume:
    name: shared-volume
  mpc-data:
    name: mpc-data
