services:
  launcher:
    image: nearone/mpc-launcher@sha256:56881591b91d324d78392f805752ecb640c773a4d62c7ae43b5fd671f6296555
    container_name: "${LAUNCHER_IMAGE_NAME}"

    environment:
      - PLATFORM=NONTEE
      - DOCKER_CONTENT_TRUST=1
      - DEFAULT_IMAGE_DIGEST=sha256:952e056156102f614db979a812ec10ed98187a206533ffc1740008768e889c15 # config digest for nearone/mpc-node:2262-port-node-launcher-to-rust-v2-140ba52

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./user-config.toml:/tapp/user_config:ro
      - shared-volume:/mnt/shared
      - mpc-data:/data

    security_opt:
      - no-new-privileges:true

    read_only: true
    tmpfs:
      - /tmp

volumes:
  shared-volume:
    name: shared-volume
  mpc-data:
    name: mpc-data
