version: '3.8'

services:
  launcher:
    image: nearone/mpc-launcher@sha256:40d78e393b51ec42a9a4964fb9cef72f499503430b626c1a8e874d4a5b3f55c9

    container_name: launcher

    environment:
      - DOCKER_CONTENT_TRUST=1
      - DEFAULT_IMAGE_DIGEST=sha256:a348eed6ec52f59a7e5f0f84406a3e3bea9d6d909eab6eaf692d4a8f4158a1a6

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dstack.sock:/var/run/dstack.sock
      - /tapp:/tapp:ro
      - shared-volume:/mnt/shared:ro

    security_opt:
      - no-new-privileges:true

    read_only: true

    tmpfs:
      - /tmp

volumes:
  shared-volume:
    name: shared-volume