services:
  launcher:
    image: nearone/mpc-launcher@sha256:56881591b91d324d78392f805752ecb640c773a4d62c7ae43b5fd671f6296555
    container_name: "${LAUNCHER_IMAGE_NAME}"

    environment:
      - PLATFORM=NONTEE
      - DOCKER_CONTENT_TRUST=1
      - DEFAULT_IMAGE_DIGEST=sha256:689ad0f37a5a9db75eeb93cb15ad4bb507883412f891a4fd19448ada575c8237 # config digest for nearone/mpc-node:main-6ee90e0

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./user-config.toml:/tapp/user_config:ro
      - shared-volume:/mnt/shared
      - mpc-data:/data

    security_opt:
      - no-new-privileges:true

    read_only: true
    tmpfs:
      - /tmp

volumes:
  shared-volume:
    name: shared-volume
  mpc-data:
    name: mpc-data
