version: '3.8'

services:
  launcher:
    image: nearone/mpc-launcher@sha256:1a91d24fca91a6e9afb539891ca9fe1171dbbc26a900497edd697b70d5763221

    container_name: launcher

    environment:
      - DOCKER_CONTENT_TRUST=1
      - DEFAULT_IMAGE_DIGEST=sha256:a348eed6ec52f59a7e5f0f84406a3e3bea9d6d909eab6eaf692d4a8f4158a1a6

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dstack.sock:/var/run/dstack.sock
      - /tapp:/tapp:ro
      - shared-volume:/mnt/shared:ro

    security_opt:
      - no-new-privileges:true

    read_only: true

    tmpfs:
      - /tmp

volumes:
  shared-volume:
    name: shared-volume