version: '3.8'

services:
  launcher:
    image: nearone/mpc-launcher@sha256:85a4fa6d1eec05e8f43dba17d3f4368f89719a2a06b9e2051d84813c3f651068

    container_name: launcher

    environment:
      - PLATFORM=TEE
      - DOCKER_CONTENT_TRUST=1
      - DEFAULT_IMAGE_DIGEST=sha256:952e056156102f614db979a812ec10ed98187a206533ffc1740008768e889c15

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dstack.sock:/var/run/dstack.sock
      - /tapp:/tapp:ro
      - shared-volume:/mnt/shared:ro

    security_opt:
      - no-new-privileges:true

    read_only: true

    tmpfs:
      - /tmp

volumes:
  shared-volume:
    name: shared-volume
