version: '3.8'

services:
  launcher:
    image: nearone/mpc-launcher@sha256:5973f1b0510f580ec1cada64310a430f4d7a380a69e57493b055bbb9cdd6ae63

    container_name: launcher

    environment:
      - PLATFORM=TEE
      - DOCKER_CONTENT_TRUST=1
      - DEFAULT_IMAGE_DIGEST=sha256:a9a874255739ab610513a570e8af9daf4f0a774781a0e13120d9b09c4106ce65 # 3.7.0

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dstack.sock:/var/run/dstack.sock
      - /tapp:/tapp:ro
      - shared-volume:/mnt/shared:ro

    security_opt:
      - no-new-privileges:true

    read_only: true

    tmpfs:
      - /tmp

volumes:
  shared-volume:
    name: shared-volume
