services:
  launcher:
    image: nearone/mpc-launcher@sha256:296da33b9336ffcb31503a6640e827bca785025225f7bbc16e7b632a7ab26cfb # 3.4.1
    container_name: "${LAUNCHER_IMAGE_NAME}"

    environment:
      - PLATFORM=NONTEE
      - DOCKER_CONTENT_TRUST=1
      - DEFAULT_IMAGE_DIGEST=sha256:ab8501e10e208eeb713c6dc8618ef8ec5d4cfe5111285eedbbc459ab18ad4122 # 3.3.2 release

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./user-config.conf:/tapp/user_config:ro
      - shared-volume:/mnt/shared
      - mpc-data:/data

    security_opt:
      - no-new-privileges:true

    read_only: true
    tmpfs:
      - /tmp

volumes:
  shared-volume:
    name: shared-volume
  mpc-data:
    name: mpc-data
