[launcher_config]
image_tags = ["3.6.0"]
image_name = "nearone/mpc-node"
registry = "registry.hub.docker.com"
rpc_request_timeout_secs = 10
rpc_request_interval_secs = 1
rpc_max_attempts = 20

[docker_command_config.port_mappings]
ports = [
    { src = 8080, dst = 8080 },
    { src = 3030, dst = 3030 },
    { src = 80, dst = 80 },
    { src = 24567, dst = 24567 },
]

[mpc_config]
home_dir = "/data"

[mpc_config.secrets]
secret_store_key_hex = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

[mpc_config.tee.authority]
type = "local"

[mpc_config.node]
my_near_account_id = "mpc-3-barak-launch1-b654bfa0a52e.5035bf56abb0.testnet"
near_responder_account_id = "mpc-3-barak-launch1-b654bfa0a52e.5035bf56abb0.testnet"
number_of_responder_keys = 1
web_ui = "0.0.0.0:8080"
migration_web_ui = "0.0.0.0:8078"
cores = 4

[mpc_config.node.indexer]
validate_genesis = false
sync_mode = "Latest"
concurrency = 1
mpc_contract_id = "mpc-contract-barak-launch1-4c5e2fe1fb42.5035bf56abb0.testnet"
finality = "optimistic"

[mpc_config.node.triple]
concurrency = 2
desired_triples_to_buffer = 128
timeout_sec = 60
parallel_triple_generation_stagger_time_sec = 1

[mpc_config.node.presignature]
concurrency = 4
desired_presignatures_to_buffer = 64
timeout_sec = 60

[mpc_config.node.signature]
timeout_sec = 60

[mpc_config.node.ckd]
timeout_sec = 60
