[package]
name = "interfaces"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
dcap-qvl = { workspace = true }
dstack-sdk = { workspace = true }
derive_more = { workspace = true }
hex = { workspace = true }
k256 = { workspace = true }
mpc-primitives = { workspace = true }
near-sdk = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
sha3 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
test_utils = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
schemars = { workspace = true, optional = true }

[features]
abi = ["schemars"]
