version: '3.8'

services:
  launcher:
    image: nearone/mpc-launcher@sha256:40d78e393b51ec42a9a4964fb9cef72f499503430b626c1a8e874d4a5b3f55c9

    container_name: launcher

    environment:
      - DOCKER_CONTENT_TRUST=1
      - DEFAULT_IMAGE_DIGEST=sha256:dd4f9adb9645f44a6c369ff4a6b4a42d8a64bae134b30842784e86de47d37e85

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dstack.sock:/var/run/dstack.sock
      - /tapp:/tapp:ro
      - shared-volume:/mnt/shared:ro

    security_opt:
      - no-new-privileges:true

    read_only: true

    tmpfs:
      - /tmp

volumes:
  shared-volume:
    name: shared-volume