use std::sync::LazyLock;

// Include the built.rs file generated by the build script
pub mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

// Re-export the constants we need
pub static MPC_VERSION: &str = built_info::PKG_VERSION;
pub static MPC_BUILD_TIME: &str = built_info::BUILT_TIME_UTC;
pub static RUSTC_VERSION: &str = built_info::RUSTC_VERSION;

// Handle the Option type for git commit
pub static MPC_COMMIT: LazyLock<&str> = LazyLock::new(|| {
    built_info::GIT_COMMIT_HASH_SHORT.unwrap_or("unknown")
});

pub static MPC_VERSION_STRING: LazyLock<String> = LazyLock::new(|| {
    format!(
        "mpc-node {}\n(release {}) (build_time {}) (commit {}) ({})",
        MPC_VERSION, MPC_VERSION, MPC_BUILD_TIME, *MPC_COMMIT, RUSTC_VERSION,
    )
});
