use clap::Parser;
use std::sync::LazyLock;
use tracing::init_logging;

mod assets;
#[cfg(test)]
mod async_testing;
mod background;
mod cli;
mod config;
mod coordinator;
mod db;
mod indexer;
mod key_events;
mod keyshare;
mod metrics;
mod mpc_client;
mod network;
mod p2p;
mod primitives;
mod protocol;
mod protocol_version;
mod providers;
mod runtime;
mod sign_request;
pub mod signing;
mod tee;
#[cfg(test)]
mod tests;
mod tracing;
mod tracking;
mod web;

// Include build information generated by the built crate
pub mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

pub static MPC_VERSION_STRING: LazyLock<String> = LazyLock::new(|| {
    format!(
        "mpc-node {}\n(release {}) (build_time {}) (commit {}) (rustc {})",
        built_info::PKG_VERSION,
        built_info::PKG_VERSION,
        built_info::BUILT_TIME_UTC,
        built_info::GIT_VERSION.unwrap_or("unknown"),
        built_info::RUSTC_VERSION,
    )
});

fn main() -> anyhow::Result<()> {
    init_logging();

    // Initialize build info metric
    metrics::init_build_info_metric();

    // Handle version flags before parsing CLI
    let args: Vec<String> = std::env::args().collect();
    if args.len() > 1 && (args[1] == "--version" || args[1] == "-V") {
        println!("{}", *MPC_VERSION_STRING);
        return Ok(());
    }

    // Parse CLI arguments
    let cli = cli::Cli::parse();
    futures::executor::block_on(cli.run())
}
