[package]
name = "test-parallel-contract"
version = "0.2.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = { workspace = true }
near-sdk = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
k256 = { workspace = true }


[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true }
