#!/usr/bin/env bash
#
# Asserts two invariants on the launcher Docker Compose templates:
#
#  1. Both templates render with no leftover `{{...}}` placeholders. Catches
#     a typo or missing placeholder added to one template.
#
#  2. The structural diff between the TEE and non-TEE renders (with the
#     same dummy digests) matches a checked-in snapshot
#     (`crates/contract/assets/templates-tee-vs-nontee.diff.snap`). Catches
#     a change to one template without a deliberate update to the other.
#
# The snapshot is regenerated by running this script with
# `UPDATE_SNAPSHOT=1`.
#
# Run from the repo root.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
RENDER="$SCRIPT_DIR/render-launcher-compose.sh"
SNAPSHOT="$SCRIPT_DIR/launcher-templates-tee-vs-nontee.diff.snap"

[ -x "$RENDER" ] || { echo "Missing render script: $RENDER" >&2; exit 3; }
[ -f "$SNAPSHOT" ] || { echo "Missing snapshot: $SNAPSHOT" >&2; exit 3; }

dummy_launcher="sha256:$(printf '%.0sa' {1..64})"
dummy_mpc="sha256:$(printf '%.0sb' {1..64})"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

LAUNCHER_MANIFEST_DIGEST="$dummy_launcher" MPC_MANIFEST_DIGEST="$dummy_mpc" \
  "$RENDER" --tee    --out "$tmp/tee.yaml"
LAUNCHER_MANIFEST_DIGEST="$dummy_launcher" MPC_MANIFEST_DIGEST="$dummy_mpc" \
  "$RENDER" --nontee --out "$tmp/nontee.yaml"

# Placeholder hygiene: the render script itself errors on unfilled
# placeholders, but double-check the output anyway.
for f in "$tmp/tee.yaml" "$tmp/nontee.yaml"; do
  if grep -q '{{' "$f"; then
    echo "❌ Rendered $f still contains placeholders:" >&2
    grep '{{' "$f" >&2
    exit 1
  fi
done

diff -u --label tee --label nontee "$tmp/tee.yaml" "$tmp/nontee.yaml" > "$tmp/actual.diff" || true

if [ "${UPDATE_SNAPSHOT:-0}" = "1" ]; then
  cp "$tmp/actual.diff" "$SNAPSHOT"
  echo "Updated snapshot: $SNAPSHOT"
  exit 0
fi

if diff -u "$SNAPSHOT" "$tmp/actual.diff"; then
  echo "✅ Template structural diff matches snapshot"
else
  echo
  echo "❌ Template structural diff does not match snapshot." >&2
  echo "   One template was changed without a matching intentional change to the other," >&2
  echo "   or the snapshot is stale. If the new diff is intentional, regenerate with:" >&2
  echo "     UPDATE_SNAPSHOT=1 $0" >&2
  exit 1
fi
