#!/usr/bin/env bash
set -euo pipefail

# Fail if any tracked non-exempt file ends a line with whitespace.
# Pattern follows tokio-rs/tokio's CI check; uses `git grep` so the
# scope is exactly "tracked files" (skips local virtualenvs, vendored
# libs/, build artefacts) and exemptions mirror the repo's .editorconfig.
#
# Exempt:
#   - *.snap, *.snap.new              insta snapshots (whitespace can be meaningful)
#   - Cargo.lock                      auto-generated
#   - third-party-licenses/licenses.html   generated by `cargo about`

if git grep -InP '\s$' -- \
     ':!*.snap' ':!*.snap.new' \
     ':!Cargo.lock' \
     ':!third-party-licenses/licenses.html'
then
  echo 'Trailing whitespace found. Please remove it.'
  exit 1
fi
