#!/usr/bin/env bash
set -euo pipefail

# Fail if any tracked non-exempt file ends a line with whitespace.
# Pattern follows tokio-rs/tokio's CI check; uses `git grep` so the
# scope is exactly "tracked files" (skips local virtualenvs, vendored
# libs/, build artefacts) and exemptions mirror the repo's .editorconfig.
#
# Exempt:
#   - *.snap, *.snap.new                    insta snapshots (whitespace can be meaningful)
#   - Cargo.lock                            auto-generated
#   - third-party-licenses/licenses.html    generated by `cargo about`

# Capture output and exit code without letting `set -e` abort on the
# expected non-zero exits (1 = no match, 2+ = real error).
set +e
output=$(git grep -InP '\s$' -- \
  ':!*.snap' ':!*.snap.new' \
  ':!Cargo.lock' \
  ':!third-party-licenses/licenses.html')
rc=$?
set -e

case "$rc" in
  0)
    echo "$output"
    echo 'Trailing whitespace found. Please remove it.'
    exit 1
    ;;
  1)
    # No matches; clean.
    ;;
  *)
    echo "git grep failed with exit $rc" >&2
    exit "$rc"
    ;;
esac
