{
 "title": "Multichain MPC Cluster",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "chain_id",
    "query": {
     "query": "label_values(up{binary=\"mpc-node\"},chain_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Signature Time Elapsed (Percentiles)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "app": "grafana-assistant-app",
     "expr": "histogram_quantile(0.50, sum by(le, chain_id) (rate(near_mpc_signature_time_elapsed_bucket{chain_id=~\"$chain_id\"}[$__rate_interval])))",
     "legendFormat": "p50 – {{chain_id}}"
    },
    {
     "app": "grafana-assistant-app",
     "expr": "histogram_quantile(0.90, sum by(le, chain_id) (rate(near_mpc_signature_time_elapsed_bucket{chain_id=~\"$chain_id\"}[$__rate_interval])))",
     "legendFormat": "p90 – {{chain_id}}"
    },
    {
     "app": "grafana-assistant-app",
     "expr": "histogram_quantile(0.99, sum by(le, chain_id) (rate(near_mpc_signature_time_elapsed_bucket{chain_id=~\"$chain_id\"}[$__rate_interval])))",
     "legendFormat": "p99 – {{chain_id}}"
    }
   ]
  },
  {
   "title": "Cluster signatures failure increase 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "delta(mpc_cluster_failed_signatures_count{chain_id=~\"$chain_id\", job=\"multichain\"}[5m])",
     "legendFormat": "{{chain_id}} {{reason}}"
    }
   ]
  },
  {
   "title": "nodes lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Signature responses per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(chain_id) (rate(mpc_num_signature_responses_indexed{chain_id=~\"$chain_id\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} {{chain_id}}"
    }
   ]
  },
  {
   "title": "MPC Binary version",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "mpc_node_build_info{chain_id=~\"$chain_id\", job!=\"tee-mpc\"} ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sign tx success rate (RPC E2E)",
   "type": "timeseries",
   "description": "Transaction's success rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(tx_bench_successful_tx_total{network=~\"$chain_id\", kind=~\"mpc-sign.*\"}[15m]) / rate(tx_bench_attempted_tx_total{network=~\"$chain_id\", kind=~\"mpc-sign.*\"}[15m])",
     "legendFormat": "{{kind}} - {{network}}"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "description": "Average latency of a transaction",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time((rate(tx_bench_tx_latency_seconds_sum{network=~\"$chain_id\",kind=~\"mpc-sign.*\"}[$__rate_interval]) / rate(tx_bench_tx_latency_seconds_count{network=~\"$chain_id\"}[$__rate_interval]))[$__rate_interval:])",
     "legendFormat": "{{kind}}, {{network}}"
    }
   ]
  },
  {
   "title": "near-indexer lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Peers lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expression": "$B - $A", "type": "math" }
   ]
  },
  {
   "title": "Signature requestes leader",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(result,chain_id, instance) (rate(mpc_num_signature_computations_led{chain_id=~\"$chain_id\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} {{chain_id}}  {{ result}}"
    }
   ]
  },
  {
   "title": "Peers lag full view",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expression": "$B - $A", "type": "math" }
   ]
  },
  {
   "title": "Owned Presignatures Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "mpc_owned_num_presignatures_available{chain_id=~\"$chain_id\", job=\"multichain\"}",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  {
   "title": "Account balances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "account_balance{chain_id=~\"$chain_id\"}",
     "legendFormat": "{{chain_id}} {{account_id}}"
    }
   ]
  },
  {
   "title": "Owned Triples Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "mpc_owned_num_triples_available{chain_id=~\"$chain_id\", job=\"multichain\"}",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  {
   "title": "Peer connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by(peer_participant_id, chain_id) (mpc_network_live_connections{chain_id=~\"$chain_id\", job=\"multichain\"})",
     "legendFormat": "{{chain_id}} - peer {{peer_participant_id}}"
    }
   ]
  },
  {
   "title": "Offline assets (should be zero)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "mpc_owned_num_presignatures_with_offline_participant{chain_id=~\"$chain_id\", job=~\"multichain|mpc_operators\"}",
     "legendFormat": "presignatures {{chain_id}} {{instance}}"
    },
    {
     "expr": "mpc_owned_num_triples_with_offline_participant{chain_id=~\"$chain_id\", job=~\"multichain|mpc_operators\"}",
     "legendFormat": "triples {{chain_id}} {{instance}}"
    }
   ]
  },
  {
   "title": "Passive Signature Requests received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rate(mpc_num_passive_signature_requests_received{chain_id=~\"$chain_id\"}[$__rate_interval])",
     "legendFormat": "{{instance}} {{chain_id}}"
    }
   ]
  },
  {
   "title": "Cluster network connectivity",
   "type": "timeseries",
   "description": "Should be always 1",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "mpc_network_live_connections{chain_id=~\"$chain_id\", job=~\"multichain|mpc_operators\"}",
     "legendFormat": "{{chain_id}} {{instance}} {{peer_participant_id}}"
    }
   ]
  },
  {
   "title": "Signature Requests Indexed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "rate(mpc_num_signature_requests_indexed{chain_id=~\"$chain_id\"}[$__rate_interval])",
     "legendFormat": "{{instance}} {{chain_id}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (connection_direction, instance) (rate(mpc_p2p_tcp_write_size_bytes_sum{job=~\"mpc_operators|multichain\", chain_id=~\"$chain_id\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - {{connection_direction}}"
    }
   ]
  },
  {
   "title": "MPC UP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "up{chain_id=~\"$chain_id\", binary=\"mpc-node\", job!=\"tee-mpc\"}",
     "legendFormat": "{{chain_id}} {{instance}}"
    }
   ]
  },
  {
   "title": "Signature Responses Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "sum by(outcome, chain_id) (rate(mpc_outgoing_transaction_outcomes{chain_id=~\"$chain_id\", type=\"respond\"}[$__rate_interval]))",
     "legendFormat": "{{chain_id}} {{outcome}}"
    }
   ]
  },
  {
   "title": "mpc-node running",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "up{chain_id=~\"$chain_id\", job=~\"multichain\"}",
     "legendFormat": "{{node_id}}"
    }
   ]
  },
  {
   "title": "Testnet Signature time elapsed bucket(Histogram)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "near_mpc_signature_time_elapsed_bucket{chain_id=\"testnet\",le=~\"0.5|0.1|0.01\"}\r\n",
     "legendFormat": "{{node_id}} le:{{le}}"
    }
   ]
  },
  {
   "title": "MPC memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "near_memory_usage_bytes{chain_id=~\"$chain_id\", binary=\"mpc-node\", job!=\"tee-mpc\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Testnet Signature time elapsed bucket (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "expr": "near_mpc_signature_time_elapsed_bucket{chain_id=\"testnet\",le=~\"0.5|0.1|0.01\"}",
     "legendFormat": "{{node_id}}-le: {{le}}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "near_sync_status{chain_id=~\"$chain_id\", job=\"multichain\"}",
     "legendFormat": "{{ node_id }}"
    }
   ]
  },
  {
   "title": "Testnet Signature time elapsed bucket ",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "near_mpc_signature_time_elapsed_bucket{chain_id=~\"testnet\",le=~\"0.5|0.1|0.01\"}\r\n",
     "legendFormat": "le:{{le}}"
    }
   ]
  },
  {
   "title": "Mainnet Signature time elapsed bucket (Heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "near_mpc_signature_time_elapsed_bucket{chain_id=\"mainnet\",le=~\"0.5|0.1|0.01\"}",
     "legendFormat": "{{node_id}}-le: {{le}}"
    }
   ]
  },
  {
   "title": "Mainnet Signature time elapsed bucket ",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "targets": [
    {
     "expr": "near_mpc_signature_time_elapsed_bucket{chain_id=\"mainnet\",le=~\"0.5|0.1|0.01\"}\r\n",
     "legendFormat": "le:{{le}}"
    }
   ]
  },
  {
   "title": "Mainnet Signature time elapsed bucket(Histogram)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "avg by(le) (increase(near_mpc_signature_time_elapsed_bucket{chain_id=\"mainnet\", le=~\"0.5|0.1|0.01\"}[$__rate_interval]))",
     "legendFormat": "{{node_id}} le:{{le}}"
    }
   ]
  }
 ]
}