[launcher_config]
image_reference = "nearone/mpc-node"
port_mappings = [
    { host = 8080, container = 8080 },
    { host = 24566, container = 24566 },
    { host = 13002, container = 13002 },
]

[mpc_node_config]
home_dir = "/data"

[mpc_node_config.log]
format = "plain"
filter = "info"

[mpc_node_config.near_init]
chain_id = "mpc-localnet"
boot_nodes = ""
genesis_path = "/app/localnet-genesis.json"
download_genesis = false

[mpc_node_config.secrets]
secret_store_key_hex = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
backup_encryption_key_hex = "0000000000000000000000000000000000000000000000000000000000000000"

[mpc_node_config.node]
my_near_account_id = "sam.test.near"
near_responder_account_id = "sam.test.near"
number_of_responder_keys = 1
web_ui = "0.0.0.0:8080"
migration_web_ui = "0.0.0.0:8078"
cores = 4

[mpc_node_config.node.indexer]
validate_genesis = false
sync_mode = "Latest"
concurrency = 1
mpc_contract_id = "mpc-contract.test.near"
finality = "optimistic"

[mpc_node_config.node.triple]
concurrency = 2
desired_triples_to_buffer = 128
timeout_sec = 60
parallel_triple_generation_stagger_time_sec = 1

[mpc_node_config.node.presignature]
concurrency = 4
desired_presignatures_to_buffer = 64
timeout_sec = 60

[mpc_node_config.node.signature]
timeout_sec = 60

[mpc_node_config.node.ckd]
timeout_sec = 60
