#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


def yaml_quote(value: str) -> str:
    escaped = value.replace('\\', '\\\\').replace('"', '\\"')
    return f"\"{escaped}\""


def load_config(config_path: Path) -> dict:
    with config_path.open() as fh:
        return json.load(fh)


def ensure_nodes(config: dict) -> None:
    nodes = config.get("nodes") or []
    defaults = config.get("defaults") or {}
    node_count = int(config.get("node_count") or 0)
    web_ui_base = int(defaults.get("web_ui_port_base") or 8080)
    p2p_base = int(defaults.get("p2p_port_base") or 3000)

    if not nodes:
        for i in range(1, node_count + 1):
            nodes.append(
                {
                    "name": f"mpc-node-{i}",
                    "service_name": f"mpc-node-{i}",
                    "account_id": f"mpc-node-{i}.test.near",
                    "image": defaults.get("node_image"),
                    "image_hash": defaults.get("node_image_hash"),
                    "secret_store_key": defaults.get("secret_store_key"),
                    "web_ui_port": web_ui_base + i,
                    "p2p_port": p2p_base + (i - 1),
                }
            )
    else:
        for i, node in enumerate(nodes, start=1):
            node.setdefault("name", f"mpc-node-{i}")
            node.setdefault("service_name", node["name"])
            node.setdefault("account_id", f"{node['name']}.test.near")
            node.setdefault("image", defaults.get("node_image"))
            node.setdefault("image_hash", defaults.get("node_image_hash"))
            node.setdefault("secret_store_key", defaults.get("secret_store_key"))
            node.setdefault("web_ui_port", web_ui_base + i)
            node.setdefault("p2p_port", p2p_base + (i - 1))

    config["nodes"] = nodes


def derive_boot_nodes(repo_root: Path, config: dict) -> str:
    if config.get("boot_nodes"):
        return config["boot_nodes"]
    node_key_path = repo_root / "deployment/localnet/node_key.json"
    with node_key_path.open() as fh:
        node_key = json.load(fh)
    return f"{node_key['public_key']}@neard:24566"


def generate_compose(config: dict, config_path: Path, repo_root: Path) -> str:
    ensure_nodes(config)
    boot_nodes = derive_boot_nodes(repo_root, config)

    neard_image = config.get("neard", {}).get("image", "nearprotocol/neard:latest")
    rpc_port = int(config.get("neard", {}).get("rpc_port", 3030))
    bootstrap_image = config.get("bootstrap", {}).get("image", "mpc-localnet-bootstrap:local")
    bootstrap_contract_path = config.get("bootstrap", {}).get("contract_path", "/artifacts/mpc_contract.wasm")
    contract_id = config.get("contract_id")

    lines = []
    def add(line: str, indent: int = 0) -> None:
        lines.append("  " * indent + line)

    add("# Generated by scripts/localnet/generate-compose.py")
    add("version: \"3.8\"")
    add("services:")

    add("neard:", 1)
    add(f"image: {neard_image}", 2)
    add("container_name: mpc-localnet-neard", 2)
    add("ports:", 2)
    add(f"- {yaml_quote(str(rpc_port) + ':3030')}", 3)
    add("volumes:", 2)
    add("- near-data:/root/.near", 3)
    add("- ./deployment/localnet:/seed:ro", 3)
    add("command:", 2)
    add("- /bin/sh", 3)
    add("- -c", 3)
    add("- |", 3)
    add("  mkdir -p /root/.near/mpc-localnet", 4)
    add("  cp -rf /seed/. /root/.near/mpc-localnet", 4)
    add("  neard --home /root/.near/mpc-localnet run", 4)

    add("bootstrap:", 1)
    add(f"image: {bootstrap_image}", 2)
    add("depends_on:", 2)
    add("- neard", 3)
    add("volumes:", 2)
    add("- near-data:/root/.near", 3)
    add("- near-credentials:/root/.near-credentials", 3)
    add("- ./deployment/localnet:/seed:ro", 3)
    add("- ./docs/localnet:/work/docs:ro", 3)
    add("- ./scripts:/work/scripts:ro", 3)
    add("- ./deployment/localnet/compose:/config:ro", 3)
    add("- ./target/near:/artifacts:ro", 3)
    add("environment:", 2)
    add(f"- LOCALNET_CONFIG=/config/{config_path.name}", 3)
    add(f"- MPC_CONTRACT_PATH={bootstrap_contract_path}", 3)
    add("command:", 2)
    add("- /work/scripts/localnet/bootstrap.sh", 3)

    for node in config["nodes"]:
        service = node["service_name"]
        account_id = node["account_id"]
        image = node["image"]
        image_hash = node.get("image_hash", "")
        secret_store_key = node.get("secret_store_key", "")
        web_ui_port = int(node["web_ui_port"])
        p2p_port = int(node["p2p_port"])

        add(f"{service}:", 1)
        add(f"image: {image}", 2)
        add("depends_on:", 2)
        add("- neard", 3)
        add("environment:", 2)
        add("- MPC_ENV=mpc-localnet", 3)
        add(f"- MPC_ACCOUNT_ID={account_id}", 3)
        add(f"- MPC_CONTRACT_ID={contract_id}", 3)
        add("- MPC_HOME_DIR=/data", 3)
        if secret_store_key:
            add(f"- MPC_SECRET_STORE_KEY={secret_store_key}", 3)
        if image_hash:
            add(f"- MPC_IMAGE_HASH={image_hash}", 3)
        add("- MPC_LATEST_ALLOWED_HASH_FILE=/data/latest_hash.txt", 3)
        add("- MPC_LOCAL_ADDRESS=0.0.0.0", 3)
        add(f"- NEAR_BOOT_NODES={boot_nodes}", 3)
        add("- RUST_LOG=info", 3)
        add("volumes:", 2)
        add(f"- {service}-data:/data", 3)
        add("ports:", 2)
        add(f"- {yaml_quote(str(web_ui_port) + ':8080')}", 3)
        add(f"- {yaml_quote(str(p2p_port) + ':3000')}", 3)

    add("volumes:")
    add("near-data:", 1)
    add("near-credentials:", 1)
    for node in config["nodes"]:
        add(f"{node['service_name']}-data:", 1)

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate docker-compose for localnet")
    parser.add_argument(
        "--config",
        default="deployment/localnet/compose/localnet.config.json",
        help="Path to localnet config JSON",
    )
    parser.add_argument(
        "--output",
        default="deployment/localnet/compose/docker-compose.yaml",
        help="Path to write docker-compose YAML",
    )
    args = parser.parse_args()

    config_path = Path(args.config).resolve()
    repo_root = Path(__file__).resolve().parents[2]

    config = load_config(config_path)
    compose = generate_compose(config, config_path, repo_root)

    output_path = Path(args.output)
    output_path.write_text(compose)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
