[package]
name = "test-migration-contract"
version = "0.1.0"
edition = "2021"
license = "MIT"

[package.metadata.cargo-shear]
ignored = ["borsh"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = { workspace = true }
near-sdk = { workspace = true }
