name: Python Code Style Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Python code formatting with Black
        uses: psf/black@stable
        with:
          options: "--check --diff --verbose"
          src: "./pytest"
