name: Docker Build and Publish MPC TEE enabled Image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      build-ref:
        default: 'main'
        description: "The branch, tag or SHA to build MPC TEE enabled Docker image from. Default to latest commit on main branch."
        type: string
    

jobs:
  docker-image-build:
    name: "Build and push MPC TEE enabled Docker image"
    runs-on: warp-ubuntu-2204-x64-2x
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.build-ref }}
        
      - name: Get short SHA
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
  
      - name: Sanitize build-ref for Docker tags
        shell: bash
        run: |
          # Replace forward slashes with hyphens to create valid Docker tags
          sanitized_ref=$(echo "${{ github.event.inputs.build-ref }}" | sed 's/\//-/g')
          echo "sanitized_ref=$sanitized_ref" >> "$GITHUB_ENV"

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push MPC Docker image to Docker Hub
        uses: Warpbuilds/build-push-action@v6
        with:
          context: .
          profile-name: "mpc-image-builder"
          push: true
          file: deployment/Dockerfile-tee-gcp
          tags: nearone/mpc-node-gcp:latest-tee,nearone/mpc-node-gcp:${{ env.sanitized_ref }}-tee,nearone/mpc-node-gcp:${{ env.sanitized_ref }}-${{ env.sha_short }}-tee
