name: Build Docker Launcher Image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-images:
    name: "Build and push Docker launcher image with commit hash"
    runs-on: warp-ubuntu-2404-x64-8x
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Allow unprivileged user namespaces (needed by repro-env/podman on Ubuntu 24.04)
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo liblzma-dev podman

      - name: Install repro-env
        run: |
          wget 'https://github.com/kpcyrd/repro-env/releases/download/v0.4.3/repro-env'
          echo '2a00b21ac5e990e0c6a0ccbf3b91e34a073660d1f4553b5f3cda2b09cc4d4d8a  repro-env' | sha256sum -c -
          sudo install -m755 repro-env -t /usr/bin

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
          cache-provider: "warpbuild"

      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Rust launcher image
        run: |
          export RUST_LAUNCHER_IMAGE_NAME=mpc-launcher
          ./deployment/build-images.sh --rust-launcher --push
