name: Python Code Style Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run YAPF to format the python code
        uses: block42-blockchain-company/yapf-action
        with:
          args: --verbose
